using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DripUI.SourceGen
{
    [Generator]
    public sealed class AlpineToIslandGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // List EVERY file the generator can see (for debugging)
            var allFiles = context.AdditionalTextsProvider
                .Where(static f => true);

            context.RegisterSourceOutput(allFiles.Collect(), (spc, files) =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// ");
                sb.AppendLine($"// DripUI.SourceGen File Discovery - {files.Length} files seen");

                for (int i = 0; i < files.Length; i++)
                {
                    var f = files[i];
                    var fileName = Path.GetFileNameWithoutExtension(f.Path) ?? $"file{i}";
                    // sanitize filename to remove invalid chars
                    var safeName = string.Concat(fileName.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_'));
                    var hintName = $"{safeName}_{i}.g.cs";

                    // var hintName = $"{safeName}_{ComputeHash(f.Path)}.g.cs";

                    var content = new StringBuilder(sb.ToString());
                    content.AppendLine($"// → {fileName} | {f.Path}");

                    spc.AddSource(hintName, SourceText.From(content.ToString(), Encoding.UTF8));
                }

                spc.AddSource("DripUI_SourceGen_FileDiscovery.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            });

            // context.RegisterSourceOutput(allFiles.Collect(), (spc, files) =>
            // {
            //     var sb = new StringBuilder();
            //     sb.AppendLine("// <auto-generated />");
            //     sb.AppendLine($"// DripUI.SourceGen File Discovery - {files.Length} files seen");
            //
            //     foreach (var f in files)
            //     {
            //         var fileName = Path.GetFileNameWithoutExtension(f.Path);
            //         sb.AppendLine($"// → {fileName} | {f.Path}");
            //
            //         // IT's this line right here that fucks it up. I just don't know how!
            //         spc.AddSource($"{fileName}.g.cs",
            //             SourceText.From(sb.ToString(), Encoding.UTF8));
            //     }
            //
            //     spc.AddSource("DripUI_SourceGen_FileDiscovery.g.cs",
            //         SourceText.From(sb.ToString(), Encoding.UTF8));
            //
            //
            //     spc.AddSource("Foo_Bar_Baz.g.cs",
            //         SourceText.From(sb.ToString(), Encoding.UTF8));
            //
            //
            //     for (int i = 0; i < 10; i++)
            //     {
            //         spc.AddSource($"example-{i}.html.g.cs",
            //             SourceText.From(sb.ToString(), Encoding.UTF8));
            //     }
            // });
        }
    }
}


//
// [Generator]
// public class MySourceGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         // Collect all files in the project
//         var allFiles = context.AdditionalTextsProvider;
//
//         // Register the source output
//         context.RegisterSourceOutput(allFiles.Collect(), (spc, files) =>
//         {
//             var sb = new StringBuilder();
//             sb.AppendLine("// <auto-generated />");
//             sb.AppendLine($"// DripUI.SourceGen File Discovery - {files.Length} files seen");
//
//             foreach (var file in files)
//             {
//                 // Process each file and generate new source code
//                 var generatedCode = GenerateCodeFromFile(file);
//                 spc.AddSource($"{file.Path}.g.cs", generatedCode);
//             }
//
//             spc.AddSource("DripUI_SourceGen_FileDiscovery.g.cs",
//                 SourceText.From(sb.ToString(), Encoding.UTF8));
//         });
//     }
//
//     private string GenerateCodeFromFile(AdditionalText file)
//     {
//         // Logic to read the file and generate code
//         var content = file.GetText().ToString();
//         return
//             $"// Generated code from {file.Path}\npublic static class GeneratedClass {{ public static string Content => \"{content}\"; }}";
//     }
// }

// [Generator]
//     public sealed class AlpineToIslandGenerator_Discovery : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             var allFiles = context.AdditionalTextsProvider
//                 .Where(f => f.Path.Contains("/Pines/", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.EndsWith(".pines.html", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.EndsWith(".html", StringComparison.OrdinalIgnoreCase) && f.Path.Contains("Pines"));
//
//             context.RegisterSourceOutput(allFiles.Collect(), (spc, files) =>
//             {
//                 var sb = new StringBuilder();
//                 sb.AppendLine("// <auto-generated />");
//                 // sb.AppendLine($"// DripUI.SourceGen File Discovery - {files.Length} files seen");
//
//                 foreach (var file in files.OrderBy(f => f.Path))
//                 {
//                     string path = file.Path;
//                     var content = file.GetText()?.ToString();
//
//                     var componentName = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//                     // Generate Island TagHelper
//                     var islandCode = GenerateIsland(componentName, content, path);
//                     spc.AddSource($"{componentName}Island.g.cs", SourceText.From(islandCode, Encoding.UTF8));
//
//                     // Generate minimal handler stub
//                     var handlerCode = GenerateHandlerStub(componentName);
//                     spc.AddSource($"{componentName}Handler.g.cs", SourceText.From(handlerCode, Encoding.UTF8));
//                 }
//
//                 // spc.AddSource("DripUI_SourceGen_FileDiscovery.g.cs",
//                 //     SourceText.From(sb.ToString(), Encoding.UTF8));
//             });
//         }
//
//
//         private static string GenerateIsland(string name, string alpineHtml, string originalPath)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                      // <auto-generated />
//                      // Source: {{originalPath}}
//
//                      using Microsoft.AspNetCore.Razor.TagHelpers;
//                      using Drip.UI.TagHelpers;
//
//                      namespace Drip.UI.GeneratedIslands
//                      {
//                          [HtmlTargetElement("{{lower}}")]
//                          public class {{name}}Island : IslandTagHelper
//                          {
//                              public {{name}}Island()
//                              {
//                                  Event = IslandEvents.Intersect;   // default: load when scrolled into view
//                                  Swap = IslandSwaps.OuterHTML;
//                                  Url = "/{{lower}}";
//                              }
//
//                              public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                              {
//                                  output.TagName = "div";
//                                  output.Content.SetHtmlContent(@"
//                      {{EscapeForVerbatimString(alpineHtml)}}
//                                  ");
//
//                                  await base.ProcessAsync(context, output);
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string GenerateHandlerStub(string name)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                      // <auto-generated />
//                      // Minimal HTMX handler for {{name}}
//
//                      using Microsoft.AspNetCore.Mvc;
//
//                      namespace Drip.UI.Handlers
//                      {
//                          public class {{name}}Handler : Controller
//                          {
//                              [HttpGet("/{{lower}}")]
//                              public IActionResult OnGet(string? viewname = null)
//                              {
//                                  return viewname is not null ? PartialView(viewname) : View();
//                              }
//
//                              [HttpPost("/{{lower}}")]
//                              public IActionResult OnPost(string? value = null, string? viewname = null)
//                              {
//                                  // Self-updating / CRUD logic goes here
//                                  return viewname is not null ? PartialView(viewname) : View();
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input)) return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }

// namespace Drip.UI.SourceGen
// {
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             // This always runs — no dependency on AdditionalTextsProvider
//             context.RegisterPostInitializationOutput(ctx =>
//             {
//                 var source = """
//                              // <auto-generated />
//                              // DripUI.SourceGen is ALIVE and running from Drip.UI project
//                              // If you see this file, the generator works.
//                              """;
//
//                 ctx.AddSource("DripUI_SourceGen_Alive.g.cs",
//                     SourceText.From(source, Encoding.UTF8));
//             });
//         }
//     }
// }

//
// namespace Drip.UI.SourceGen
// {
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             // Extremely broad filter + full diagnostics
//             var allCandidateFiles = context.AdditionalTextsProvider
//                 .Where(f => true); // see EVERYTHING first
//
//             context.RegisterSourceOutput(allCandidateFiles.Collect(), (spc, files) =>
//             {
//                 var sb = new StringBuilder();
//                 sb.AppendLine("// <auto-generated />");
//                 sb.AppendLine("// DripUI.SourceGen - File Discovery Debug");
//                 sb.AppendLine("// Total files seen: " + files.Length);
//                 sb.AppendLine();
//
//                 foreach (var f in files)
//                 {
//                     var filename = Path.GetFileName(f.Path);
//                     sb.AppendLine($"// → {filename} | {f.Path}");
//                 }
//
//                 spc.AddSource("DripUI_SourceGen_FileDiscovery.g.cs",
//                     SourceText.From(sb.ToString(), Encoding.UTF8));
//             });
//
//             // Now the real Pines filter
//             var pinesFiles = context.AdditionalTextsProvider
//                 .Where(f => f.Path.Contains("Pines", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.EndsWith(".html", StringComparison.OrdinalIgnoreCase));
//
//             var fileContents = pinesFiles.Select((file, ct) =>
//             {
//                 var path = file.Path;
//                 var content = file.GetText(ct)?.ToString() ?? string.Empty;
//                 return (path, content);
//             });
//
//             context.RegisterSourceOutput(fileContents, (spc, state) =>
//             {
//                 var (path, alpineHtml) = state;
//                 var name = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//
//                 var islandCode = GenerateIsland(name, alpineHtml, path);
//                 spc.AddSource($"{name}Island.g.cs", SourceText.From(islandCode, Encoding.UTF8));
//
//                 var handlerCode = GenerateHandlerStub(name);
//                 spc.AddSource($"{name}Handler.g.cs", SourceText.From(handlerCode, Encoding.UTF8));
//             });
//         }
//
//         // ... keep your existing GenerateIsland, GenerateHandlerStub, SafeIdentifier, EscapeForVerbatimString methods ...
//         private static string GenerateIsland(string name, string alpineHtml, string originalPath)
//         {
//             var lower = name.ToLowerInvariant();
//             return $$"""
//                      // <auto-generated />
//                      // Source: {{originalPath}}
//
//                      using Microsoft.AspNetCore.Razor.TagHelpers;
//                      using Drip.UI.TagHelpers;
//
//                      namespace Drip.UI.GeneratedIslands
//                      {
//                          [HtmlTargetElement("{{lower}}")]
//                          public class {{name}}Island : IslandTagHelper
//                          {
//                              public {{name}}Island()
//                              {
//                                  Event = IslandEvents.Intersect;
//                                  Swap = IslandSwaps.OuterHTML;
//                                  Url = "/{{lower}}";
//                              }
//
//                              public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                              {
//                                  output.TagName = "div";
//                                  output.Content.SetHtmlContent(@"
//                      {{EscapeForVerbatimString(alpineHtml)}}
//                                  ");
//                                  await base.ProcessAsync(context, output);
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string GenerateHandlerStub(string name)
//         {
//             var lower = name.ToLowerInvariant();
//             return $$"""
//                      // <auto-generated />
//                      using Microsoft.AspNetCore.Mvc;
//
//                      namespace Drip.UI.Handlers
//                      {
//                          public class {{name}}Handler : Controller
//                          {
//                              [HttpGet("/{{lower}}")]
//                              public IActionResult OnGet(string? viewname = null) => viewname is not null ? PartialView(viewname) : View();
//
//                              [HttpPost("/{{lower}}")]
//                              public IActionResult OnPost(string? value = null, string? viewname = null) => viewname is not null ? PartialView(viewname) : View();
//                          }
//                      }
//                      """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input)) return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }
// }

//
// namespace Drip.UI.SourceGen
// {
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             // Broader filter + diagnostics
//             var pinesFiles = context.AdditionalTextsProvider
//                 .Where(f => f.Path.Contains("Pines", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.EndsWith(".html", StringComparison.OrdinalIgnoreCase));
//
//             var fileContents = pinesFiles.Select((file, ct) =>
//             {
//                 var path = file.Path;
//                 var content = file.GetText(ct)?.ToString() ?? string.Empty;
//                 return (path, content);
//             });
//
//             context.RegisterSourceOutput(fileContents, (spc, state) =>
//             {
//                 var (path, alpineHtml) = state;
//                 var componentName = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//
//                 var islandCode = GenerateIsland(componentName, alpineHtml, path);
//                 spc.AddSource($"{componentName}Island.g.cs", SourceText.From(islandCode, Encoding.UTF8));
//
//                 var handlerCode = GenerateHandlerStub(componentName);
//                 spc.AddSource($"{componentName}Handler.g.cs", SourceText.From(handlerCode, Encoding.UTF8));
//             });
//
//             // Always generate diagnostics so we know it's alive
//             context.RegisterPostInitializationOutput(ctx =>
//             {
//                 ctx.AddSource("DripUI_SourceGen_Diagnostics.g.cs", SourceText.From("""
//                     // <auto-generated />
//                     // DripUI.SourceGen is running and seeing Pines files!
//                     """, Encoding.UTF8));
//             });
//         }
//
//         private static string GenerateIsland(string name, string alpineHtml, string originalPath)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                      // <auto-generated />
//                      // Source: {{originalPath}}
//
//                      using Microsoft.AspNetCore.Razor.TagHelpers;
//                      using Drip.UI.TagHelpers;
//
//                      namespace Drip.UI.GeneratedIslands
//                      {
//                          [HtmlTargetElement("{{lower}}")]
//                          public class {{name}}Island : IslandTagHelper
//                          {
//                              public {{name}}Island()
//                              {
//                                  Event = IslandEvents.Intersect;   // load on scroll into view
//                                  Swap = IslandSwaps.OuterHTML;
//                                  Url = "/{{lower}}";
//                              }
//
//                              public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                              {
//                                  output.TagName = "div";
//                                  output.Content.SetHtmlContent(@"
//                      {{EscapeForVerbatimString(alpineHtml)}}
//                                  ");
//
//                                  await base.ProcessAsync(context, output);
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string GenerateHandlerStub(string name)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                      // <auto-generated />
//                      // Handler for {{name}}
//
//                      using Microsoft.AspNetCore.Mvc;
//
//                      namespace Drip.UI.Handlers
//                      {
//                          public class {{name}}Handler : Controller
//                          {
//                              [HttpGet("/{{lower}}")]
//                              public IActionResult OnGet(string? viewname = null)
//                              {
//                                  return viewname is not null ? PartialView(viewname) : View();
//                              }
//
//                              [HttpPost("/{{lower}}")]
//                              public IActionResult OnPost(string? value = null, string? viewname = null)
//                              {
//                                  // Self-updating / CRUD logic here
//                                  return viewname is not null ? PartialView(viewname) : View();
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input)) return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }
// }

// namespace Drip.UI.SourceGen
// {
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             // Extremely broad filter for debugging
//             var allFiles = context.AdditionalTextsProvider
//                 .Where(f => f.Path.Contains("Pines", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.EndsWith(".html", StringComparison.OrdinalIgnoreCase));
//
//             var fileContents = allFiles.Select((file, ct) =>
//             {
//                 var path = file.Path;
//                 var content = file.GetText(ct)?.ToString() ?? string.Empty;
//                 return (path, content);
//             });
//
//             context.RegisterSourceOutput(fileContents, (spc, state) =>
//             {
//                 var (path, content) = state;
//                 var name = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//
//                 var islandCode = GenerateIsland(name, content, path);
//                 spc.AddSource($"{name}Island.g.cs", SourceText.From(islandCode, Encoding.UTF8));
//             });
//
//             // Diagnostic file - always generated so we know the generator ran
//             context.RegisterPostInitializationOutput(ctx =>
//             {
//                 ctx.AddSource("DripUI_SourceGen_Diagnostics.g.cs", SourceText.From("""
//                     // <auto-generated />
//                     // DripUI.SourceGen Diagnostics
//
//                     namespace DripUI.SourceGen
//                     {
//                         public static class Diagnostics
//                         {
//                             public const string Message = "DripUI.SourceGen is running!";
//                         }
//                     }
//                     """, Encoding.UTF8));
//             });
//         }
//
//         private static string GenerateIsland(string name, string alpineHtml, string originalPath)
//         {
//             var lower = name.ToLowerInvariant();
//             return $$"""
//                      // <auto-generated />
//                      // Source: {{originalPath}}
//
//                      using Microsoft.AspNetCore.Razor.TagHelpers;
//                      using Drip.UI.TagHelpers;
//
//                      namespace Drip.UI.GeneratedIslands
//                      {
//                          [HtmlTargetElement("{{lower}}")]
//                          public class {{name}}Island : IslandTagHelper
//                          {
//                              public {{name}}Island()
//                              {
//                                  Event = IslandEvents.Intersect;
//                                  Swap = IslandSwaps.OuterHTML;
//                                  Url = "/{{lower}}";
//                              }
//
//                              public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                              {
//                                  output.TagName = "div";
//                                  output.Content.SetHtmlContent(@"
//                      {{EscapeForVerbatimString(alpineHtml)}}
//                                  ");
//                                  await base.ProcessAsync(context, output);
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input)) return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }
// }


//
// namespace Drip.UI.SourceGen
// {
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             // Pick up every Pines component
//             var pinesFiles = context.AdditionalTextsProvider
//                 .Where(static f =>
//                     f.Path.Contains("/Pines/", StringComparison.OrdinalIgnoreCase) ||
//                     f.Path.EndsWith(".pines.html", StringComparison.OrdinalIgnoreCase));
//
//             var fileContents = pinesFiles.Select((file, ct) =>
//             {
//                 var path = file.Path;
//                 var content = file.GetText(ct)?.ToString() ?? string.Empty;
//                 return (path, content);
//             });
//
//             context.RegisterSourceOutput(fileContents, (spc, state) =>
//             {
//                 var (path, alpineHtml) = state;
//                 var componentName = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//
//                 // Generate the Island TagHelper
//                 var islandCode = GenerateIsland(componentName, alpineHtml, path);
//                 spc.AddSource($"{componentName}Island.g.cs",
//                     SourceText.From(islandCode, Encoding.UTF8));
//
//                 // Generate the minimal backend handler stub
//                 var handlerCode = GenerateHandlerStub(componentName);
//                 spc.AddSource($"{componentName}Handler.g.cs",
//                     SourceText.From(handlerCode, Encoding.UTF8));
//             });
//         }
//
//         private static string GenerateIsland(string name, string alpineHtml, string originalPath)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                 // <auto-generated />
//                 // Source: {{originalPath}}
//
//                 using Microsoft.AspNetCore.Razor.TagHelpers;
//                 using Drip.UI.TagHelpers;
//
//                 namespace Drip.UI.GeneratedIslands
//                 {
//                     /// <summary>
//                     /// Auto-generated htmx Island from Pines {{name}}
//                     /// Loads on intersect (scroll into view) by default
//                     /// </summary>
//                     [HtmlTargetElement("{{lower}}")]
//                     public class {{name}}Island : IslandTagHelper
//                     {
//                         public {{name}}Island()
//                         {
//                             Event = IslandEvents.Intersect;
//                             Swap = IslandSwaps.OuterHTML;
//                             Url = "/{{lower}}";
//                         }
//
//                         public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                         {
//                             output.TagName = "div";
//                             output.Content.SetHtmlContent(@"
//                 {{EscapeForVerbatimString(alpineHtml)}}
//                             ");
//
//                             await base.ProcessAsync(context, output);
//                         }
//                     }
//                 }
//                 """;
//         }
//
//         private static string GenerateHandlerStub(string name)
//         {
//             var lower = name.ToLowerInvariant();
//
//             return $$"""
//                 // <auto-generated />
//                 // Minimal HTMX handler for {{name}}
//
//                 using Microsoft.AspNetCore.Mvc;
//
//                 namespace Drip.UI.Handlers
//                 {
//                     public class {{name}}Handler : Controller
//                     {
//                         [HttpGet("/{{lower}}")]
//                         public IActionResult OnGet(string? viewname = null)
//                         {
//                             return viewname is not null
//                                 ? PartialView(viewname)
//                                 : View();
//                         }
//
//                         [HttpPost("/{{lower}}")]
//                         public IActionResult OnPost(string? value = null, string? viewname = null)
//                         {
//                             // Self-updating input / CRUD logic goes here
//                             // You can return full view or partial via viewname parameter
//                             return viewname is not null
//                                 ? PartialView(viewname)
//                                 : View();
//                         }
//                     }
//                 }
//                 """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input)) return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }
// }


//
// namespace Drip.UI.SourceGen
// {
//     using System.Text;
//     using Microsoft.CodeAnalysis;
//     using Microsoft.CodeAnalysis.Text;
//
//
//     [Generator]
//     public sealed class AlpineToIslandGenerator : IIncrementalGenerator
//     {
//         public void Initialize(IncrementalGeneratorInitializationContext context)
//         {
//             var pinesFiles = context.AdditionalTextsProvider
//                 .Where(f => f.Path.EndsWith(".pines.html", StringComparison.OrdinalIgnoreCase) ||
//                             f.Path.Contains("/Pines/")
//                 );
//
//             var fileContents = pinesFiles.Select((file, ct) =>
//             {
//                 var path = file.Path;
//                 var content = file.GetText(ct)?.ToString() ?? string.Empty;
//                 return (path, content);
//             });
//
//             context.RegisterSourceOutput(fileContents, (spc, state) =>
//             {
//                 var (path, alpineHtml) = state;
//                 var componentName = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
//
//                 var generatedTagHelper = GenerateTagHelper(componentName, alpineHtml, path);
//                 var generatedHandlerStub = GenerateHandlerStub(componentName);
//
//                 spc.AddSource($"{componentName}Island.g.cs",
//                     SourceText.From(generatedTagHelper, Encoding.UTF8));
//
//                 spc.AddSource($"{componentName}Handler.g.cs",
//                     SourceText.From(generatedHandlerStub, Encoding.UTF8));
//             });
//         }
//
//         private static string GenerateTagHelper(string name, string alpineHtml, string originalPath)
//         {
//             return $$"""
//                      // <auto-generated />
//                      // Source: {{originalPath}}
//
//                      using Microsoft.AspNetCore.Razor.TagHelpers;
//                      using Drip.UI.TagHelpers;
//
//                      namespace Drip.UI.GeneratedIslands
//                      {
//                          [HtmlTargetElement("{{name.ToLowerInvariant()}}")]
//                          public class {{name}}Island : IslandTagHelper
//                          {
//                              public {{name}}Island()
//                              {
//                                  Event = IslandEvents.Intersect;   // default: loads on scroll into view
//                                  Swap = IslandSwaps.OuterHTML;
//                                  Url = "/{{name.ToLowerInvariant()}}";  // your handler endpoint
//                              }
//
//                              public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
//                              {
//                                  output.TagName = "div";
//                                  output.Content.SetHtmlContent(@"
//                      {{EscapeForVerbatimString(alpineHtml)}}
//                                  ");
//
//                                  await base.ProcessAsync(context, output);
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string GenerateHandlerStub(string name)
//         {
//             var lower = name.ToLowerInvariant();
//             return $$"""
//                      // <auto-generated />
//                      // Minimal HTMX handler stub for {{name}}
//
//                      using Microsoft.AspNetCore.Mvc;
//
//                      namespace Drip.UI.Handlers
//                      {
//                          public class {{name}}Handler : Controller
//                          {
//                              [HttpGet("/{{lower}}")]
//                              public IActionResult OnGet(string? viewname = null)
//                              {
//                                  // Return full component or partial view
//                                  return viewname is not null
//                                      ? PartialView(viewname)
//                                      : View();
//                              }
//
//                              [HttpPost("/{{lower}}")]
//                              public IActionResult OnPost([FromForm] string? value, string? viewname = null)
//                              {
//                                  // Self-updating input example
//                                  // TODO: your business logic here
//
//                                  return viewname is not null
//                                      ? PartialView(viewname)
//                                      : View();
//                              }
//                          }
//                      }
//                      """;
//         }
//
//         private static string SafeIdentifier(string input)
//         {
//             if (string.IsNullOrEmpty(input))
//                 return "Component";
//             return new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
//         }
//
//         private static string EscapeForVerbatimString(string s)
//             => (s ?? string.Empty).Replace("\"", "\"\"");
//     }
// }
