using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CodeMechanic.Embeds.SourceGen;

[Generator]
public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            var source = GenerateEmbeddedResources();
            ctx.AddSource("CodeMechanic_Embeds_Resources.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateEmbeddedResources()
    {
        return """
            // <auto-generated />
            #nullable enable

            namespace CodeMechanic.Embeds
            {
                /// <summary>
                /// Strongly-typed embedded resource references.
                /// Generated by CodeMechanic.Embeds.SourceGen
                /// </summary>
                public static partial class Embedded
                {
                    public static readonly SourceFile PackageReferenceTemplate = new()
                    {
                        Name = "package_reference.template",
                        Qualified = "sfapp.templates",
                        Extension = ".template"
                    };

                    public static readonly SourceFile RazorAppTemplate = new()
                    {
                        Name = "razor.app.template",
                        Qualified = "sfapp.templates",
                        Extension = ".template"
                    };

                    // TODO: Add more templates here as we expand glob parsing
                }
            }
            """;
    }
}



//
// namespace CodeMechanic.Embeds.SourceGen;
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              /// <summary>
//                              /// Strongly-typed embedded resources.
//                              /// Generated by CodeMechanic.Embeds.SourceGen
//                              /// </summary>
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile PackageReferenceTemplate = new()
//                                  {
//                                      Name = "package_reference.template",
//                                      Qualified = "sfapp.templates",
//                                      Extension = ".template"
//                                  };
//
//                                  public static readonly SourceFile RazorAppTemplate = new()
//                                  {
//                                      Name = "razor.app.template",
//                                      Qualified = "sfapp.templates",
//                                      Extension = ".template"
//                                  };
//
//                                  static Embedded()
//                                  {
//                                      // Optional: remove if you have a static ctor already
//                                      // Console.WriteLine("✅ CodeMechanic Embedded resources loaded!");
//                                  }
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_Resources.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }

// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              /// <summary>
//                              /// Auto-generated strongly-typed embedded resource references.
//                              /// Generated by CodeMechanic.Embeds.SourceGen v1.0.5
//                              /// </summary>
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile HelloWorldTemplate = new()
//                                  {
//                                      Name = "HelloWorld",
//                                      Qualified = "CodeMechanic.Embeds",
//                                      Extension = ".template"
//                                  };
//
//                                  // No static constructor here — avoids conflict with your real one
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }


//
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          using System;
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile HelloWorldTemplate = new()
//                                  {
//                                      Name = "HelloWorld",
//                                      Qualified = "CodeMechanic.Embeds",
//                                      Extension = ".template"
//                                  };
//
//                                  static Embedded()
//                                  {
//                                      Console.WriteLine("🚀 CodeMechanic.Embeds.SourceGen v1.0.0 - HelloWorld generator loaded from BaGetter!");
//                                  }
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }

//
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         // HelloWorld placeholder - no csproj parsing yet
//         context.RegisterPostInitializationOutput(static ctx =>
//         {
//             var source = GenerateHelloWorld();
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
//
//     private static string GenerateHelloWorld()
//     {
//         return """
//                // <auto-generated />
//                #nullable enable
//
//                using System;
//
//                namespace CodeMechanic.Embeds
//                {
//                    /// <summary>
//                    /// CodeMechanic.Embeds.SourceGen is alive and kicking on your BaGetter feed!
//                    /// </summary>
//                    public static partial class Embedded
//                    {
//                        public static readonly SourceFile HelloWorldTemplate = new()
//                        {
//                            Name = "HelloWorld",
//                            Qualified = "CodeMechanic.Embeds",
//                            Extension = ".template",
//                            // FullName will be constructed correctly by your existing logic
//                        };
//
//                        static Embedded()
//                        {
//                            Console.WriteLine("🎉 CodeMechanic.Embeds.SourceGen HelloWorld loaded successfully!");
//                        }
//                    }
//                }
//                """;
//     }
// }
